api/src/main/scala/TypeClass.scala
std/src/main/scala/ExMap.scala
std/src/main/scala/ExSet.scala

Fixes #37.
---
Super-seeds #47, which I'd opened from master by mistake.

Introduce ExSet.+ & use it to fix ExMap.+.

---

dev/src/main/scala/Cache.scala
dev/src/main/scala/System.scala
dev/src/main/scala/package.scala
doc/overview.md
project/Build.scala
std/src/main/scala/Builds.scala
std/src/main/scala/Instances.scala
std/src/main/scala/StdPackage.scala
std/src/main/scala/package.scala

Eliminate guava dependency.

---

api/src/main/scala/Trait.scala
jvm/src/main/scala/WrapJava.scala
jvm/src/main/scala/package.scala
std/src/main/scala/AtomicView.scala
std/src/main/scala/BiIterable.scala
std/src/main/scala/Conversions.scala
std/src/main/scala/Each.scala
std/src/main/scala/ForeachOps.scala
std/src/main/scala/Gateways.scala
std/src/main/scala/Linear.scala
std/src/main/scala/StdPackage.scala
std/src/main/scala/Vec.scala
std/src/main/scala/ViewOps.scala
std/src/main/scala/package.scala
std/src/main/scala/repl.scala
testOnly/src/test/scala/CollectionsSpec.scala

More work integrating vector.

---

std/src/main/scala/Vec.scala

Interesting the parameters one finds being passed all
over the place only to go completely unused.

Cleaning up Vec.

---

consoleOnly/src/main/scala/ammonite.scala
project/Build.scala

The usual frustrating experience to accomplish rocket
science like a blank line. But all's well that ends well
in this case, I hope.

Closer to working in ammonite.

---

project/dmz/src/main/scala/ScalaDmz.scala
project/testOnly/src/main/scala/Bundle.scala
std/src/main/scala/Consecutive.scala
std/src/main/scala/Index.scala
std/src/main/scala/Vec.scala
std/src/main/scala/package.scala
std/src/main/scala/vecutil.scala

Almost down to 5000 lines of code outside of test code.

More deleting.

---

std/src/main/scala/ApiExtensions.scala
std/src/main/scala/AtomicView.scala
std/src/main/scala/Show.scala
std/src/main/scala/ViewOps.scala
std/src/main/scala/Zip.scala
std/src/main/scala/package.scala

Finding all the redundant code.

Zip ergonomics.

---

project/consoleOnly/src/main/scala/ammonite.scala
project/testOnly/src/test/scala/CollectionsSpec.scala
std/src/main/scala/BiIterable.scala
std/src/main/scala/Each.scala
std/src/main/scala/ExSet.scala
std/src/main/scala/Implicits.scala
std/src/main/scala/LowLevel.scala
std/src/main/scala/Show.scala
std/src/main/scala/Size.scala
std/src/main/scala/ops/Primitive.scala
std/src/main/scala/ops/Psp.scala
std/src/main/scala/ops/TypeClass.scala
std/src/main/scala/ops/View.scala

I wonder how many codebases ever get whittled like this.

Deleting primitive ops and unused code.

---

project/testOnly/src/main/scala/OperationCounts.scala
project/testOnly/src/main/scala/ViewClass.scala
project/testOnly/src/test/scala_2.11/Typecheck.scala
project/testOnly/src/test/scala_2.11/generate.scala
std/src/main/scala/WrapJava.scala

Noticed that there were only a few left, so just a quick easy change.

Remove last references to policy

---

std/src/main/scala/Vec.scala
std/src/main/scala/vecutil.scala

See if we can eventually stomp out all the 32s, 31s,
and other magic numbers without destroying performance.
Probably betting too much on the inliner. One can really
start to appreciate the C preprocessor in these situations.

Toward block-width-polymorphism.

---

project/Build.scala
project/plugins.sbt

Fixing the sbts so you don't have to. :D

Minor build tweaks

---

api/src/main/scala/Interfaces.scala
api/src/main/scala/TypeClasses.scala
project/consoleOnly/src/main/scala/ammonite.scala
project/testOnly/src/main/scala/Generators.scala
project/testOnly/src/test/scala/CollectionsSpec.scala
project/testOnly/src/test/scala/InferenceSpec.scala
std/src/main/scala/AtomicView.scala
std/src/main/scala/Builds.scala
std/src/main/scala/Conversions.scala
std/src/main/scala/Implicits.scala
std/src/main/scala/Index.scala
std/src/main/scala/LowLevel.scala
std/src/main/scala/Pstring.scala
std/src/main/scala/StdPackage.scala
std/src/main/scala/WrapJava.scala
std/src/main/scala/Zip.scala
std/src/main/scala/ops/Primitive.scala
std/src/main/scala/ops/View.scala

Some of this is not ideal but I'm pushing it anyway.

Various work.

---

api/src/main/scala/Interfaces.scala
api/src/main/scala/TypeClasses.scala
project/testOnly/src/main/scala/OperationCounts.scala
project/testOnly/src/main/scala/Probe.scala
project/testOnly/src/test/scala/CollectionsSpec.scala
std/src/main/scala/Each.scala
std/src/main/scala/Implicits.scala
std/src/main/scala/Indexed.scala
std/src/main/scala/LowLevel.scala
std/src/main/scala/Plist.scala
std/src/main/scala/ops/Primitive.scala
std/src/main/scala/ops/View.scala

Threw out Linear as an interface. Linear things are those
which can be decomposed with an implicit Splitter.

Core interfaces.

---

project/Build.scala

Reduced the warning granularity.

Console warnings.

---

testing/src/main/scala/Bundle.scala

So for example it would show like this (in colour):
+ foo
+ ✓  bar
- ✗  baz

Move the red cross mark to align with the green check mark

---

.codecov.yml
benchmark/Benchmark.scala
std/src/main/scala/std/All.scala
std/src/main/scala/std/Array.scala
std/src/main/scala/std/Consecutive.scala
std/src/main/scala/std/ImplicitOps.scala
std/src/main/scala/std/Implicits.scala
std/src/main/scala/std/LowLevel.scala
std/src/main/scala/std/Native.scala
std/src/main/scala/std/View.scala
std/src/main/scala/std/Viewable.scala
testing/src/main/scala/Generators.scala
testing/src/main/scala/package.scala
testing/src/test/scala/CollectionsSpec.scala
testing/src/test/scala/ViewsVsEager.scala

Rework Consecutive.

---

std/src/main/scala/api/Api.scala
std/src/main/scala/api/Interfaces.scala
std/src/main/scala/api/TypeClasses.scala
std/src/main/scala/std/All.scala
std/src/main/scala/std/Array.scala
std/src/main/scala/std/Builds.scala
std/src/main/scala/std/Classes.scala
std/src/main/scala/std/Consecutive.scala
std/src/main/scala/std/HashEqOrder.scala
std/src/main/scala/std/Helpers.scala
std/src/main/scala/std/Implicits.scala
std/src/main/scala/std/Pstring.scala
std/src/main/scala/std/View.scala
testing/src/test/scala/CollectionsSpec.scala

AISLE VIEW, GET IT?
Also Hash/Eq/Order. This needs more labor.

Cleanup on aisle view.

---

std/src/main/scala/std/ADTs.scala
std/src/main/scala/std/ExternalTypes.scala
std/src/main/scala/std/Show.scala
std/src/test/scala/tests/MiscSpec.scala

Fix showing Nths, break showing ranges..

---

.ci/run.sh
build.sbt
project/PspStd.scala
project/build.properties
std/src/main/scala/std/WalksMakes.scala

Change a letter to a nice ascii one.

---

project/PspStd.scala

The method you've been looking for..
Also - welcome back!

Use Initialize#apply instead of enriched mapValue

---

std/src/main/scala/std/Interval.scala
std/src/test/scala/tests/MiscSpec.scala

Fix Interval.point
